feat: create helper to sanitize data
melhorenvio/wp-melhorenvio-v2 pull request #102
Opened 2022-05-16 13:47 UTC by viniciustessmann

Se aplicado, esse PR tem como objetivo apender a demanda observada pela equipe do Worpress  sobre vulnerabilidades  de dados vindos de POST/GET sem o filtro de sanitize.

2022-05-16 22:11 UTC, marcalpizzi commented on Controllers/OrdersController.php
> -        $postId = $_GET['post_id'];
Em algunas lugares as variáveis estão com camelCase e outras com snake_case. O ideial seria manter em todo o código o padrão do Wordpress (que acredito ser snake_case).

2022-05-17 17:49 UTC, andrevpde90 commented on Helpers/SanitizeHelper.php
> +        }
Talvez neste caso isso daqui possa valer a pena:
https://developer.wordpress.org/reference/functions/sanitize_text_field/#comment-5504

2022-05-17 17:50 UTC, andrevpde90 commented on Controllers/QuotationController.php
> +        $result = (new QuotationService())->calculateQuotationBypost_id($post_id);
Esse método teve sua assinatura  alterada?

2022-05-17 17:51 UTC, andrevpde90 commented on Services/CartService.php
> +        $quotation = (new QuotationService())->calculateQuotationBypost_id($orderId);
Creio que esta alteração tenha sido por engano

2022-05-18 13:09 UTC, marcalpizzi requested changes
Acabou que estamos mexendo em muito arquivos sem necessidade, fugindo ao propósito do PR e aumentando o risco de criar problemas não identificados.

É uma boa dar uma diminuida, reverter partes alteradas indesejadamente, para alterar apenas o código que faz uso do _sanitizer_ criado.

2022-05-18 18:16 UTC, marcalpizzi approved these changes
LGTM

2022-05-18 18:30 UTC, merged